### ISSUE TITLE
Compilation under MSVC

### ISSUE THREAD

**Issue by ken-noland** [stetre/moonassimp#1]
I'm currently trying to build this using the MSVC toolchain(due to some other dependencies, I can not change this). Unfortunately, the __attribute__((__unused__)) is not something that can be compiled under MSVC. Instead, I would suggest putting this into the source of tree.h

```
#ifndef _WIN32
#define UNUSED __attribute__((__unused__))
#else
#define UNUSED
#endif
```

and then replace the two other occurrences of `__attribute__((__unused__))` with UNUSED. Yeah, sure, this could generate warnings for MSVC, but there are already quite a few of those so I wouldn't include that in this issue.

**Comment by stetre** [comment]
You'll likely encounter this error again if you ever try to build under MSVC any other library of this collection. In case, just reference this issue.

**Comment by ken-noland** [comment]
Thanks! I'll close this issue.
